### ISSUE TITLE
Is this project still going to get updated

### ISSUE THREAD

**Issue by redrockvp** [eraeco/party.lol#5]
Hi there, just checking in to see what the current status of this project is? Are there still plans for it or has it been abandoned?

**Comment by amark** [comment]
Still kicking! Just need more others helping. :) Tons of plans.

**Comment by amark** [comment]
@HTEredrock :)

**Comment by redrockvp** [comment]
SEA{"m":{"#":"k20muxw0cL0feJ2pyXSz~rdk2wzZLLLjKMkKbMZ3Mf-PpmtCME-J6znXsju7cQgY.yyPrhyhXTo2A9StZtzQIEhddseKp0VRQ4ffTQXiSPrU.",".":"what",":":{"ct":"4WSBIR/98epOSp55t10X43gj/8T1UsgsNPq4oLcCO+sWk4pIQ0UlTIQmPan3Hyo6YA==","iv":"fxRZh/gt38hIAh85Ch46","s":"LEuw9SK6X3qS","v":1,"w":"8FavBqkfrUs+BK3c.razs+hGwSYLo2S3X"},">":1571675241744.001},"s":"pVpIRV1WYP6WPGOYsd/xgo5wtR0WCZNJP7nKrYx7RxqM8LQpaJqqlGCtKHEOOjQHcRCGLew1xTyxY37x+w5cvQ=="}

**Comment by amark** [comment]
@HTEredrock you interested in helping contribute?

Actually doing a call with another developer in a few minutes on a new mode we want to introduce called "Public Party" at https://meet.jit.si/teamera (in like 10min)

and https://gitter.im/amark/gun or https://discord.gg/gnzgpBh is where the community hangs out, please hop in and mention joining the Party Team!

**Comment by amark** [comment]
@HTEredrock ROFL I DIDN"T EVEN NOTICE YOUR MESSAGE WAS ENCRYPTED hahaha! Want to join my private party? Install http://party.lol to read my secret post:
SEA{"m":{"#":"k20u7fosDRmsj4e0FogK~1XwPF6sfMeXwig7-QTciJNROKX1B_NulFXNnKlb60G4.KEU0paOs4VCIObxt6GkJRPv4Q9m5dNlEz73coKwqySI.",".":"what",":":{"ct":"lIyBV71os1dkNlSkfqwtROjmvZpmCLM3vW6x7Vds0riXgSglQ7TsTPjaPpUlOdOu0yqSZhFzUoelzp7//0mb3wm+5+KS12b5+whWDO/81UexUDtjcIh13npA8DDJPlSJEtXjUDvlPuJnzAc2+2PTKWHLERM0zwbMo1KE6i7FoVn5MfInVwXyZlTlF217JpgMxcwyrE4yLbg7fbJZQhZn6HbzLv/61ebY9f408aplWp4JJo08oI+b96nSttoe1lH6fV/TQruat6147hTO7mFkqKux+NBOeLJW8d4aFHEQLtBoxb8D3q2Q7vGzn5EHdvcY8HIPlQH4cO+iOf6ZFAu+oDP7cAlqYh0G98EGcwTtSKSuTv/0+ZcXbHM0hbCcUsRZ5ozf4jvfecBSL2I9LLBPDtyWpBmLIh9knS7GhXPtI9hyu+uALlxk1Wx7llO2EUYz4sMpkynRsYNOjJ6Drm74ybKp4MLPf+rBVPN3LxVdnMJzq1h8t21Dd8Zfdho4E5y/o8s2LM+HAhlXKrs2tGQpK90e8IPhOygydFvzEZwP4EC4RH8n3wgf+Tk1SvLrsomwDh07aKdS3GDNQDsCt8CqSF3jZGMZ4XhSRjaehfH2Dht73KxKytb2i7+Wxjy7fQ==","iv":"+xXKze/PkBWmTDhP9rG+","s":"k8hNbGLKxNux","v":1,"w":"CO0lNE7RDHWvCUKf.YRKnKDpNzkp0I/3Y"},">":1571687581997},"s":"PUtsWPB1QsIGf10+Lt14Dn9oNh3awFHD+stlp7QrDEqBzOISfBAYAXyDgDhMeEQVbO66E1az6UlvUUy99DjHTQ=="}

**Comment by redrockvp** [comment]
Want to join my private party? Install http://party.lol to read my secret post:
SEA{"m":{"#":"k20xo8cpwzeFIBLSiQdw~rdk2wzZLLLjKMkKbMZ3Mf-PpmtCME-J6znXsju7cQgY.yyPrhyhXTo2A9StZtzQIEhddseKp0VRQ4ffTQXiSPrU.",".":"what",":":{"ct":"xK7O719tLJDR378/njrT95GJcmSyOWI7pNOIX6KR/9uc8gYi3vtr8QbfVb6WeXROLg9N2C1IN8Ro7LHQdAvMkul1h5VBysuT3DDcS+kuZoiCowmsppQtI3hwjn701F/KAA==","iv":"cl/GP/R/4xD/OoVtS5r8","s":"GmHQnohZvD14","v":1,"w":"ab2Qp4KkJ+/TMeM0.smlx5ckbu+QJOlR0"},">":1571693404489.001},"s":"tT72c4qJzyJtJjoEau6XccVF9nNx3DSyaMO2ErVSEsp+M4+JHgAV/Rj7I38ALHnBhuv1ztmmN4rhtXcctqrEOg=="}

**Comment by redrockvp** [comment]
Want to join my private party? Install http://party.lol to read my secret post:
SEA{"m":{"#":"k20xo8cpwzeFIBLSiQdw~rdk2wzZLLLjKMkKbMZ3Mf-PpmtCME-J6znXsju7cQgY.yyPrhyhXTo2A9StZtzQIEhddseKp0VRQ4ffTQXiSPrU.",".":"what",":":{"ct":"xK7O719tLJDR378/njrT95GJcmSyOWI7pNOIX6KR/9uc8gYi3vtr8QbfVb6WeXROLg9N2C1IN8Ro7LHQdAvMkul1h5VBysuT3DDcS+kuZoiCowmsppQtI3hwjn701F/KAA==","iv":"cl/GP/R/4xD/OoVtS5r8","s":"GmHQnohZvD14","v":1,"w":"ab2Qp4KkJ+/TMeM0.smlx5ckbu+QJOlR0"},">":1571693404489.001},"s":"tT72c4qJzyJtJjoEau6XccVF9nNx3DSyaMO2ErVSEsp+M4+JHgAV/Rj7I38ALHnBhuv1ztmmN4rhtXcctqrEOg=="}

**Comment by redrockvp** [comment]
Want to join my private party? Install http://party.lol to read my secret post:
SEA{"m":{"#":"k20xo8cpwzeFIBLSiQdw~rdk2wzZLLLjKMkKbMZ3Mf-PpmtCME-J6znXsju7cQgY.yyPrhyhXTo2A9StZtzQIEhddseKp0VRQ4ffTQXiSPrU.",".":"what",":":{"ct":"xK7O719tLJDR378/njrT95GJcmSyOWI7pNOIX6KR/9uc8gYi3vtr8QbfVb6WeXROLg9N2C1IN8Ro7LHQdAvMkul1h5VBysuT3DDcS+kuZoiCowmsppQtI3hwjn701F/KAA==","iv":"cl/GP/R/4xD/OoVtS5r8","s":"GmHQnohZvD14","v":1,"w":"ab2Qp4KkJ+/TMeM0.smlx5ckbu+QJOlR0"},">":1571693404489.001},"s":"tT72c4qJzyJtJjoEau6XccVF9nNx3DSyaMO2ErVSEsp+M4+JHgAV/Rj7I38ALHnBhuv1ztmmN4rhtXcctqrEOg=="}
