### ISSUE TITLE
How can I help with the mobile version?

### ISSUE THREAD

**Issue by ohmygaugh-crypto** [eraeco/party.lol#8]
Do you still need help with this? Just lemme know

**Comment by ohmygaugh-crypto** [comment]
Want to join my private party? Install http://party.lol to read my secret post:
SEA{"m":{"#":"l6pc3iqtwz6JKAEd315l~-Dv-dU0Brq8BlfmCvwo721lKT16ugoOFJqWFkhX1FYA.DByF6KDzruAXnaehrkVqdhyw-3kMivzVMeKydvHa_18.",".":"what",":":{"ct":"cDz2Hw+kvir6dbDXW+cK8uorrIAJ8wYCwPidxfi/iaUNMKk9busTHgwZnf0PKl8=","iv":"kEX/VG4rtVoG0urmSKB2","s":"1Casj9v2zh8J","v":1,"w":"2oN98VdT+pDa/Q/n.CZsaiUN7HTou7XPU"},">":1660240114087},"s":"lY41E/muqjkSSy5mKTslKdkUCZoeWYWnapVKzu/y0NndPH7jpd49/ImFfeynjQNDY4CU4CY0jV89KUo99ULh1Q=="}

**Comment by amark** [comment]
Want to join my private party? Install http://party.lol to read my secret post:
SEA{"m":{"#":"ljggpnj0J3P6o1mQveIh~5hDdMTFEjwqlZFMkUQeRo4-X5dtIYSK2MkxnOJCwUnQ.ge9ygYwPQbsYJInlT6FLezbZxnMAP_A4thCS43uVwMQ.",".":"what",":":{"ct":"lbyXqYA0v2gMmYE06E9g1YcYAVA+PtAaMMmKW3CGWkwCKl1l3Va7qL9Sf2bOlW/FDUrHU/DqcIAmEbamK7git0yCGxMtC3AYwqpq01pTJ5toIozU+pVBT+JqyLkcMCLtFiqbVm7Cv8IN9hKCf7K7EE0rG+3JodK/Vodm6gN2Pv/wkyFIMIaPH2G+X5b6vTSUn0gLhKg9oBRKGqYrdVQhpm+WoIldjKYZb+uFwyrjcr8h6tqhdkRtAgdPlEAloFHDWSfT/Cu8UskCV6mT9SqJEEYD8tMR/f/fCQNMgwn3oNeU57/gW/px2xQyDg8dXg==","iv":"sMnA+sZKR/8HHdwJsSEr","s":"iSJOY16gEZsO","v":1,"w":"MLl2X9AYqV+fM9MJ.Svyea77fSwO44v1i"},">":1688001839965},"s":"y/nDtmmPqK2SMrA8b9E29dzyIl3TKOFL39AfJDNBptoEi7d2xR/4x7mmtUzLcfnEClt+uqYwQAHKtxYjFdT9TQ=="}

**Comment by ohmygaugh-crypto** [comment]
party.lol extension was not working so I'll just spill the tea:

I would love to! Also let's talk about "Soul mate" the knowledge graph. That appeals to me big time.

I can't dm you on twitter because I haven't payed to become a verified user lmao
